spring:
  application:
    name: eventos
    
  main.allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
     
server:
  servlet:
    context-path: /eventos
  port: 7070

amountAlertLimit: 3000